app:
  appId: "17651061"
http:
  port: "8081"
  timeout: "30000"
fakestoreproxyapi:
  host: "fake-store-proxy-api.sg-s1.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
checkoutproxyapi:
  host: "fakestore-checkout-sys-api-v1.sg-s1.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
fakestoreproductapi:
  host: "fakestore-product-prc-api-v1.sg-s1.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
layer: "prc"
version: "v1"
context: "fakestore"
syspath: "/api/sys/fakestore/v1"
prcpath: "/api/prc/fakestore/v1" 

